import { CHURCH } from './church'

/**
 * What each route tells a crawler, a link preview and a screen reader.
 *
 * The app renders on the client and has two shells, so nothing in index.html
 * can say what a given page is — every route inherited one title and one
 * description, which is the same as having neither. This is the single place
 * that decides, and scripts/seo-audit.mjs is the thing that keeps it honest.
 *
 * Written as data rather than as tags scattered through screens because the
 * two shells render the same routes from different components: a <Seo/> in
 * MobileShell's screens and another in DesktopShell's pages would be two
 * answers to one question, and they would drift.
 */

/**
 * The one host the site is canonically served from. Deliberately a constant and
 * not window.location.origin — a canonical URL that agrees with whatever host
 * you happen to be on is a canonical URL that does nothing. Keep in step with
 * SEO_ORIGIN in scripts/seo-audit.mjs and the sitemap generator.
 */
export const SITE_ORIGIN = 'https://cantica-web.onrender.com'

/** The link-preview card. Generated by scripts/make-og.mjs. */
export const OG_IMAGE = '/og-image.png'

export interface SeoMeta {
  /** Page-specific part of the title; the church name is appended. */
  title: string
  description: string
  /** Operator tools and live surfaces — kept out of results entirely. */
  noindex?: boolean
  /** Structured data for this route, beyond the site-wide church node. */
  jsonLd?: Record<string, unknown>[]
}

const SUFFIX = ` · ${CHURCH.name}`

/**
 * Title as it appears in a tab and a result. A page title over ~60 characters is
 * truncated in a SERP, so the church name is dropped rather than the part that
 * says which page this is — a song's own name carries more than the suffix does.
 */
export function fullTitle(title: string): string {
  const withSuffix = `${title}${SUFFIX}`
  return withSuffix.length <= 60 ? withSuffix : title
}

/** The church itself, as search engines model one. */
export function churchJsonLd(): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'Church',
    name: CHURCH.name,
    alternateName: CHURCH.nameTe,
    url: SITE_ORIGIN,
    logo: `${SITE_ORIGIN}/icons/pwa-512.png`,
    image: `${SITE_ORIGIN}${OG_IMAGE}`,
    description: CHURCH.welcome,
    address: {
      '@type': 'PostalAddress',
      streetAddress: '8001 Mustang Drive',
      addressLocality: 'Irving',
      addressRegion: 'TX',
      postalCode: '75038',
      addressCountry: 'US'
    },
    sameAs: [CHURCH.website],
    // The three gatherings, in the form Google reads opening hours by. A church
    // site is looked up for exactly this and nothing else surfaces it.
    openingHoursSpecification: [
      { day: 'Sunday', opens: '11:00', closes: '13:00' },
      { day: 'Wednesday', opens: '20:00', closes: '21:30' },
      { day: 'Saturday', opens: '20:00', closes: '21:30' }
    ].map((s) => ({
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: `https://schema.org/${s.day}`,
      opens: s.opens,
      closes: s.closes
    })),
    event: CHURCH.services.map((s) => ({
      '@type': 'Event',
      name: s.name,
      description: s.note,
      eventAttendanceMode: s.where.startsWith('In person')
        ? 'https://schema.org/OfflineEventAttendanceMode'
        : 'https://schema.org/OnlineEventAttendanceMode',
      location: s.where.startsWith('In person')
        ? { '@type': 'Place', name: CHURCH.name, address: CHURCH.address }
        : { '@type': 'VirtualLocation', url: CHURCH.website }
    }))
  }
}

/**
 * The routes, and what each one is for.
 *
 * Descriptions are written to be read in a result, not to repeat the title —
 * and they must be unique, because a shared description across eleven routes
 * tells a search engine those are eleven copies of one page.
 */
export const ROUTE_SEO: Record<string, SeoMeta> = {
  '/': {
    title: `${CHURCH.city} · Telugu church`,
    description: `A warm, Christ-centered Telugu church in ${CHURCH.city}. Worship Sundays at 11 AM, Bible study Wednesdays, prayer Saturdays — in person and online.`,
    jsonLd: [churchJsonLd()]
  },
  '/about': {
    title: 'About us',
    description:
      'A Telugu Christian family in Dallas–Fort Worth, and the three things we gather to do: worship in our heart language, open the Word, and care for one another.',
    jsonLd: [churchJsonLd()]
  },
  '/services': {
    title: 'Service times',
    description:
      'Worship Service Sunday 11 AM in person, Bible Study Wednesday 8 PM on Zoom, and Saturday Prayer 8 PM. All are welcome at every one.',
    jsonLd: [churchJsonLd()]
  },
  '/visit': {
    title: 'Plan your visit',
    description: `Visiting for the first time? Where to park, what to wear, what to expect, and what happens on a Sunday at ${CHURCH.address}.`,
    jsonLd: [churchJsonLd()]
  },
  '/give': {
    title: 'Give',
    description:
      'Support the ministry of Telugu Community Church. Gifts are handled through Zeffy, so 100% of what you give reaches the church.',
    jsonLd: [churchJsonLd()]
  },
  '/watch': {
    title: 'Watch live',
    description:
      'Follow the Sunday service live in Telugu — with the songs, scripture and message on your own screen, at home or across the world.'
  },
  '/bible': {
    title: 'Read the Bible in Telugu & English',
    description:
      'The whole Bible side by side in Telugu and English, with adjustable text and full offline reading once the app has been opened.'
  },
  '/songs': {
    title: 'Telugu worship songbook',
    description:
      'Search thousands of Telugu worship songs by title or by any line of the lyrics, in Telugu script or romanised spelling. Works offline.'
  },
  '/more': {
    title: 'More',
    description:
      'Service times, directions, giving, notifications, installing the app, and the tools our worship team uses on a Sunday.'
  },
  '/install': {
    title: 'Add the app to your phone',
    description:
      'Install Telugu Community Church on an iPhone, an Android phone or a computer, or share it with your prayer group.'
  },
  '/notifications': {
    title: 'Notifications',
    description: 'Be told the moment a service goes live, and nothing else. Turn it on or off from any device you use.'
  },

  // -- not for search results ------------------------------------------------
  // Tools for three people. A visitor searching for the church who lands on the
  // slide controller is a worse outcome than not being found at all.
  '/build': {
    title: 'Service Builder',
    description: "Pick Sunday's songs and readings for Cantica.",
    noindex: true
  },
  '/remote': {
    title: 'Operator remote',
    description: 'Drive the live slides from a phone.',
    noindex: true
  },
  '/notify': {
    title: 'Send a notification',
    description: 'Tell the church something.',
    noindex: true
  }
}

/** Prefix rules for the routes that carry an id, checked before the table. */
const DYNAMIC: { test: (p: string) => boolean; meta: SeoMeta }[] = [
  {
    // The song's own screen fills these in; this is what it shows meanwhile,
    // and what a crawler gets if the songbook chunk never resolves.
    test: (p) => p.startsWith('/songs/'),
    meta: { title: 'Song', description: 'A song from the Telugu Community Church worship songbook.' }
  },
  {
    test: (p) => p.startsWith('/c/') || p.startsWith('/live/'),
    meta: {
      title: 'Live service',
      description: 'The service as it is happening.',
      noindex: true
    }
  }
]

export function seoFor(pathname: string): SeoMeta {
  const exact = ROUTE_SEO[pathname]
  if (exact) return exact
  const dynamic = DYNAMIC.find((d) => d.test(pathname))
  if (dynamic) return dynamic.meta
  // An unknown path redirects to home; describe it as home rather than leaving
  // the previous route's tags standing.
  return ROUTE_SEO['/']
}

// ------------------------------------------------------------ head writer ---
/**
 * Tags this module owns, so it can rewrite them without disturbing the ones
 * index.html sets for the installed app (theme-color, apple-* and friends).
 */
const OWNED = 'data-seo'

function upsert(tag: 'meta' | 'link', keyAttr: string, key: string, valueAttr: string, value: string): void {
  const sel = `${tag}[${keyAttr}="${key}"]`
  let el = document.head.querySelector(sel)
  if (!el) {
    el = document.createElement(tag)
    el.setAttribute(keyAttr, key)
    el.setAttribute(OWNED, '')
    document.head.appendChild(el)
  }
  el.setAttribute(valueAttr, value)
}

function applyToHead(meta: SeoMeta, pathname: string): void {
  const title = fullTitle(meta.title)
  const url = `${SITE_ORIGIN}${pathname}`
  const image = `${SITE_ORIGIN}${OG_IMAGE}`

  document.title = title
  upsert('meta', 'name', 'description', 'content', meta.description)
  upsert('link', 'rel', 'canonical', 'href', url)
  // Absent means indexable; only ever say noindex, never "index".
  upsert('meta', 'name', 'robots', 'content', meta.noindex ? 'noindex, nofollow' : 'index, follow')

  upsert('meta', 'property', 'og:type', 'content', 'website')
  upsert('meta', 'property', 'og:site_name', 'content', CHURCH.name)
  upsert('meta', 'property', 'og:title', 'content', title)
  upsert('meta', 'property', 'og:description', 'content', meta.description)
  upsert('meta', 'property', 'og:url', 'content', url)
  upsert('meta', 'property', 'og:image', 'content', image)
  upsert('meta', 'property', 'og:image:alt', 'content', `${CHURCH.name} — ${CHURCH.city}`)
  upsert('meta', 'property', 'og:locale', 'content', 'en_US')
  upsert('meta', 'property', 'og:locale:alternate', 'content', 'te_IN')

  upsert('meta', 'name', 'twitter:card', 'content', 'summary_large_image')
  upsert('meta', 'name', 'twitter:title', 'content', title)
  upsert('meta', 'name', 'twitter:description', 'content', meta.description)
  upsert('meta', 'name', 'twitter:image', 'content', image)

  // One managed JSON-LD block, replaced wholesale — merging would leave the
  // previous route's structured data describing this one.
  const existing = document.head.querySelector(`script[${OWNED}][type="application/ld+json"]`)
  if (meta.jsonLd?.length) {
    const script = existing ?? document.createElement('script')
    script.setAttribute('type', 'application/ld+json')
    script.setAttribute(OWNED, '')
    script.textContent = JSON.stringify(meta.jsonLd.length === 1 ? meta.jsonLd[0] : meta.jsonLd)
    if (!existing) document.head.appendChild(script)
  } else {
    existing?.remove()
  }
}

/**
 * Two layers, merged rather than sequenced: the route's own answer, and an
 * override from a screen that only knows its title once data has loaded. A
 * merge is used because React runs a child's effect before its parent's, so a
 * screen writing directly to the head would be overwritten by the route a
 * moment later.
 */
type Layer = 'route' | 'screen'
const layers = new Map<Layer, Partial<SeoMeta>>()
let currentPath = '/'

function flush(): void {
  const base = layers.get('route') ?? ROUTE_SEO['/']
  const over = layers.get('screen') ?? {}
  applyToHead({ ...(base as SeoMeta), ...over }, currentPath)
}

export function setRouteSeo(pathname: string): void {
  currentPath = pathname
  layers.set('route', seoFor(pathname))
  // A new route invalidates whatever the last screen said about itself.
  layers.delete('screen')
  flush()
}

export function setScreenSeo(meta: Partial<SeoMeta> | null): void {
  if (meta) layers.set('screen', meta)
  else layers.delete('screen')
  flush()
}
